"""Shared helpers for reading this repository's SysML v2 model.

These helpers are deliberately not a SysML v2 parser. They recognise only the
modeling conventions used in this repository, as described in
method/02-stakeholders-and-needs.md, and they never modify the model.
"""

import os
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent

DOC = re.compile(r"doc\s*/\*(.*?)\*/", re.DOTALL)

# The conventions of this repository, see method/02-stakeholders-and-needs.md.
CONCERN_DEF = re.compile(r"#extendedConcern\s+concern\s+def\s+(\w+)\s*\{")
STAKEHOLDER_DEF = re.compile(r"#extendedStakeholder\s+part\s+def\s+(\w+)\s*\{")
STAKEHOLDER_PARAM = re.compile(r"stakeholder\s+\w+\s*:\s*([\w:]+)\s*;")


def enum_values(body, attribute):
    """Return the enum literals assigned to a redefined attribute."""
    pattern = r"attribute\s*:>>\s*" + attribute + r"\s*=\s*\w+::(\w+)\s*;"
    return re.findall(pattern, body)


def fail(model, line, message):
    """Abort with a message that points at the offending model element."""
    sys.exit(f"{Path(sys.argv[0]).stem}: {model}:{line}: {message}")


def read_model(model):
    try:
        return model.read_text(encoding="utf-8")
    except OSError as error:
        sys.exit(f"{Path(sys.argv[0]).stem}: cannot read {model}: {error}")


def definition_blocks(text, header):
    """Yield (name, body, line) for each definition matching `header`.

    Definitions are yielded in model order. `body` is None when the definition
    is not closed, so that callers can report it.
    """
    for match in header.finditer(text):
        depth, end = 1, match.end()
        while depth and end < len(text):
            depth += {"{": 1, "}": -1}.get(text[end], 0)
            end += 1
        line = text.count("\n", 0, match.start()) + 1
        yield match.group(1), None if depth else text[match.end():end - 1], line


def documentation(model, name, body, line):
    """Return the doc comment of a definition as a single line of prose."""
    doc = DOC.search(body)
    text = " ".join(" ".join(
        re.sub(r"^\s*\*?\s?", "", part) for part in doc.group(1).splitlines()
    ).split()) if doc else ""
    if not text:
        fail(model, line, f"'{name}' has no doc text")
    return text


def humanize(identifier):
    """ThermalRelief -> Thermal Relief, DeskWorker -> Desk Worker."""
    spaced = re.sub(r"(?<=[a-z0-9])(?=[A-Z])", " ", identifier)
    return re.sub(r"(?<=[A-Z])(?=[A-Z][a-z])", " ", spaced)


def cell(text):
    """Escape a value so that it cannot break out of a Markdown table cell."""
    return text.replace("|", "\\|")


def header_lines(title, model, output, subject):
    """The generated-file banner shared by all views."""
    try:
        label = model.resolve().relative_to(REPO).as_posix()
    except ValueError:
        label = model.name
    link = Path(os.path.relpath(model.resolve(), output.resolve().parent)).as_posix()
    return [
        "<!-- GENERATED FILE - DO NOT EDIT. -->",
        "",
        f"# {title}",
        "",
        f"Generated from [`{label}`]({link}) by `tools/{Path(sys.argv[0]).name}`.",
        "",
        "Do not edit this file. It is overwritten on every run. The SysML v2 model",
        f"is the single source of truth for {subject}.",
        "",
    ]
